CREATE TABLE "MediaTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MediaType" character varying(64) NOT NULL,
    CONSTRAINT "PK_MediaTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "NpgsqlQueries" (
    "Vec" tsvector NOT NULL
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(32) NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "Contexts" (
    "Id" uuid NOT NULL,
    "Text" character varying(512) NULL,
    "Content" bytea NULL,
    "MediaTypeId" integer NULL,
    CONSTRAINT "PK_Contexts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contexts_MediaTypes_MediaTypeId" FOREIGN KEY ("MediaTypeId") REFERENCES "MediaTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TranslationPairs" (
    "Id" uuid NOT NULL,
    "CorrelationId" character varying(256) NOT NULL,
    "Source" character varying(4096) NOT NULL,
    "SearchVector" tsvector NOT NULL,
    "Target" character varying(4096) NULL,
    "ContextId" uuid NULL,
    "ParentId" integer NOT NULL,
    CONSTRAINT "PK_TranslationPairs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TranslationPairs_Contexts_ContextId" FOREIGN KEY ("ContextId") REFERENCES "Contexts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TranslationPairs_Projects_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

INSERT INTO "MediaTypes" ("Id", "MediaType")
VALUES (1, 'image/jpeg');
INSERT INTO "MediaTypes" ("Id", "MediaType")
VALUES (2, 'image/png');

CREATE INDEX "IX_Contexts_MediaTypeId" ON "Contexts" ("MediaTypeId");

CREATE UNIQUE INDEX "IX_MediaTypes_MediaType" ON "MediaTypes" ("MediaType");

CREATE UNIQUE INDEX "IX_Projects_Name" ON "Projects" ("Name");

CREATE INDEX "IX_TranslationPairs_ContextId" ON "TranslationPairs" ("ContextId");

CREATE INDEX "IX_TranslationPairs_CorrelationId" ON "TranslationPairs" ("CorrelationId");

CREATE UNIQUE INDEX "IX_TranslationPairs_ParentId_CorrelationId" ON "TranslationPairs" ("ParentId", "CorrelationId");

SELECT setval(
    pg_get_serial_sequence('"MediaTypes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "MediaTypes") + 1,
        nextval(pg_get_serial_sequence('"MediaTypes"', 'Id'))),
    false);


ALTER TABLE "TranslationPairs" DROP CONSTRAINT "FK_TranslationPairs_Contexts_ContextId";

ALTER TABLE "TranslationPairs" ADD "CreationTime" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity';

ALTER TABLE "TranslationPairs" ADD "ModificationTime" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity';

ALTER TABLE "TranslationPairs" ADD CONSTRAINT "FK_TranslationPairs_Contexts_ContextId" FOREIGN KEY ("ContextId") REFERENCES "Contexts" ("Id") ON DELETE SET NULL;